[build]
  command = """
    npx prisma generate
    npm run build
  """
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--no-optional --no-audit --no-fund"
  NEXT_PUBLIC_SITE_URL = "https://geminicoder.netlify.app"  # Update this with your actual domain

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
