[build]
  command = """
    npm ci --include=optional --platform=linux --arch=x64
    npm run build
  """
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--include=optional --platform=linux --arch=x64"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
