[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PYTHON_VERSION = "3.9"
  CI_PYTHON_VERSION = "3.9"
  SKIP_PYTHON_SETUP = "true"
  USE_PYTHON = "false"
  NETLIFY_USE_PYTHON = "false"
  NETLIFY_EXPERIMENTAL_BUILD_RUST_WITH_PYTHON = "false"
