[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PYTHON_VERSION = "false"
  USE_PYTHON = "false"
  NETLIFY_USE_PYTHON = "false"
  NETLIFY_EXPERIMENTAL_BUILD_RUST_WITH_PYTHON = "false"
