[build]
  command = """
    npm ci
    npx prisma generate
    npm run build
  """
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.8.1"
  NPM_FLAGS = "--no-optional --no-audit --no-fund --legacy-peer-deps"
  NEXT_PUBLIC_SITE_URL = "https://geminicoder.netlify.app"  # Update this with your actual domain

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false
